### ISSUE TITLE
Something broke amass for me

### ISSUE THREAD

**Issue by sumgr0** [OWASP/Amass#260]
When trying to use amass (installed via snap) on my Debian box is giving me the error:
"Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found"

This was working few minutes back.

**Comment by phspade** [comment]
same here

**Comment by caffix** [comment]
Please try again. I have updated the paths to the new locations

**Comment by sumgr0** [comment]
Still getting the same error message.

**Comment by phspade** [comment]
Still came up with an error.

`config/config.go:616:19: undefined: os.UserConfigDir`

**Comment by caffix** [comment]
The os.UserConfigDir error is because you now need golang version 1.13 to compile

**Comment by phspade** [comment]
! FIXED !

**Comment by caffix** [comment]
Great! Thank you for the fast feedback

**Comment by sumgr0** [comment]
@caffix the original error: "Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found"
still persists

**Comment by CharlieEriksen** [comment]
Broken for me too. The fact that the binary is dependent on a github resource is really bad. That means even if you pull an old version for whatever reason, it won't work. 

Failing to pull the list shouldn't fail things.

**Comment by caffix** [comment]
You will need the binary from the new v3.1.4 release in order to properly fetch the wordlists.

We will soon be embedding the default wordlists into the binary. In the meantime, you can provide your own alteration and brute forcing wordlists via command-line flags or the configuration file

**Comment by sumgr0** [comment]
@caffix is the update available through snap now?

Doing snap refresh or snap remove amass and then snap install amass, still installs the 3.0.27 version?
