### ISSUE TITLE
Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found

### ISSUE THREAD

**Issue by godzilla74** [OWASP/Amass#271]
Using Amass v3.0.27

Updated to latest version as of 09/17/19:
  ` go get -u github.com/OWASP/Amass/...`

Attempted to perform simple `enum`:
```  
$ amass enum -d domain.com
 > Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found
```

Also tried to override wordlist (with existing wordlist):
```
$ amass enum -d domain.com -w /opt/go/src/github.com/OWASP/Amass/wordlists/all.txt
> Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found
```

**Comment by faheel** [comment]
I'm also getting `404 Not Found` on running `amass -d <domain>`on v2.9.0

**Comment by godzilla74** [comment]
@faheel I ran across this on their Discord channel:

```
Amass still hasn't been updated to to  v3.1.4 causing it to fail when trying to fetch the wordlists from the github repo. Is an update on snap expected soon? If not, a temporary fix would be keeping a copy of all the wordlists in the /wordlists/ directory. That way it will still work for those who haven't yet updated.
```

I still couldn't get it to work, even with creating a `config.ini` file to force the wordlists to use what was in that.

I did, however, get amass to work by pulling the docker container and running it through there:
```
docker pull caffix/amass:latest
docker run --rm -v $(pwd):/amass/ caffix/amass:latest enum -d <domain> -oA amass
```

**Comment by J12934** [comment]
Might be a good idea to pin the download url to the currently release so that this could not happen again in the future.

E.g. Amass 3.1.6 would always pull from `https://raw.githubusercontent.com/OWASP/Amass/v3.1.6/wordlists/alterations.txt` and not from master.

**Comment by nicholaspier** [comment]
I'm experiencing a similar issue. Amass v3.0.27 from Kali Linux repositories. I used the utility last week without issue. This seems to be very new. Can the file be re-added to its previous location? 

`# amass enum -d example.com
Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found
`

**Comment by caffix** [comment]
Please upgrade to Amass v3.1.6 that has the default wordlists embedded within the binary

**Comment by nicholaspier** [comment]
> 
> 
> Please upgrade to Amass v3.1.6 that has the default wordlists embedded within the binary

Any solution for those of us who'd prefer to use packages and let our distribution update the utilities. My opinion is that continuous pulls are not very convenient. Could we download the word lists from somewhere and reference them with the -w parameter? Or, would that not fix the issue?

**Comment by caffix** [comment]
Kali is updating the package right now. Otherwise, you'll need to obtain the update another way (download the binary for v3.1.6). This problem will not present itself again, since we are not fetching the files from the Internet any longer

**Comment by d0xo** [comment]
snapversion is still 3.0.27

**Comment by sumgr0** [comment]
@d0xo the snap has been updated. Try the cmd: snap refresh, and that shall do it.

I'm using it through snap too...

![image](https://user-images.githubusercontent.com/11391119/65117172-4ba15000-da07-11e9-96e7-6d9a30c0f3a3.png)

**Comment by d0xo** [comment]
I have updated the smapversion, had to use --beta to get it working. Snap refresh did nothing at all " All snaps are up to date"  This is on 1 Vps with Kali and One with Debian 9. both has the same snap respons.

But I did re install 3.1.6. And nothing is happening when doing amass enum -passive -d domain. 

this is for both boxes now beeing on the correct version.

**Comment by caffix** [comment]
I’ll soon be closing this issue unless there are additional questions

**Comment by ParadoxalPentest** [comment]
guys if you're using macbook try these two commands to renew it :

brew uninstall amass --force
then
brew install amass

if you don't have brew command install it first using : https://brew.sh/index_fr

That's how i fixed this in my case.
Happy hacking ✌️

**Comment by krizzsk** [comment]
Hey guys,
I have been facing the  same issue, my snaps are up to date ( using amass 3.1.9 ) and still having the issue.
Any solutions? 

OS - Debian

**Comment by caffix** [comment]
@krizzsk Can you join our Discord server so we can troubleshoot the problem you’re experiencing? Thank you

**Comment by jepunband** [comment]
hi i have the same problem. I installed in using apt-get... version 2.9.13 .

$amass -active -brute -o hosts.txt -d google.com
Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found

**Comment by J12934** [comment]
> hi i have the same problem. I installed in using apt-get... version 2.9.13 .
> 
> $amass -active -brute -o hosts.txt -d google.com
> Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found

@jepunband
Version 2.9.13 is a pretty old version
Newer versions don't have this problem anymore.
