### ISSUE TITLE
Dependency issue introduced in v3.10.5

### ISSUE THREAD

**Issue by chvancooten** [OWASP/Amass#500]
Running the following command (in Dockerfile)

```
export GO111MODULE=on \
    && go get -u github.com/OWASP/Amass/v3/...
```

Tries updating dependencies but fails with the following error.

```
go get: github.com/knq/sysutil@v0.0.0-20191005231841-15668db23d08 updating to
        github.com/knq/sysutil@v1.0.0: parsing go.mod:
        module declares its path as: github.com/chromedp/sysutil
                but was required as: github.com/knq/sysutil
```

(Refer to https://github.com/chvancooten/BugBountyScanner/issues/19) 

The new path is `github.com/chromedp/sysutil`, looks like there is a dependency issue somewhere in the old dependencies, but couldn't quite figure out the exact issue.

**Comment by jimen0** [comment]
Hi @chvancooten I pushed a patch that should fix your problem once the Amass team merges it.

Cheers,

**Comment by chvancooten** [comment]
Superb, thanks for the fix @jimen0!

**Comment by jimen0** [comment]
Hi @chvancooten it looks like you'll have to wait until the maintainer decides to push the same change I submitted ¯\_(ツ)_/¯

https://github.com/OWASP/Amass/pull/509#issuecomment-719134259

**Comment by caffix** [comment]
This has been fixed in version 3.11

**Comment by riramar** [comment]
Not sure if the bug is back or if I'm doing something wrong.

```
$ export GO111MODULE=on && go get -u -v github.com/OWASP/Amass/v3/...
go: found github.com/OWASP/Amass/v3/... in github.com/OWASP/Amass/v3 v3.11.3
go: github.com/gobuffalo/logger upgrade => v1.0.3
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.3
go: github.com/mailru/easyjson upgrade => v0.7.7
go: github.com/beorn7/perks upgrade => v1.0.1
go: github.com/spf13/cobra upgrade => v1.1.1
go: github.com/cloudflare/cloudflare-go upgrade => v0.13.8
go: github.com/tylertreat/BoomFilters upgrade => v0.0.0-20200520150052-42a7b4300c0c
go: golang.org/x/oauth2 upgrade => v0.0.0-20210201163806-010130855d6c
go: github.com/gobuffalo/packd upgrade => v1.0.0
go: github.com/miekg/dns upgrade => v1.1.38
go: github.com/golang/protobuf upgrade => v1.4.3
go: github.com/gobuffalo/packr/v2 upgrade => v2.8.1
go: google.golang.org/appengine upgrade => v1.6.7
go: github.com/chromedp/cdproto upgrade => v0.0.0-20210208055300-32adaa8323b6
go: golang.org/x/crypto upgrade => v0.0.0-20201221181555-eec23a3978ad
go: golang.org/x/text upgrade => v0.3.5
go: golang.org/x/tools upgrade => v0.1.0
go: github.com/prometheus/common upgrade => v0.15.0
go: golang.org/x/sys upgrade => v0.0.0-20210124154548-22da62e12c0c
go: github.com/rogpeppe/go-internal upgrade => v1.7.0
go: github.com/prometheus/procfs upgrade => v0.4.1
go: github.com/cenkalti/backoff upgrade => v2.2.1+incompatible
go: golang.org/x/net upgrade => v0.0.0-20210119194325-5f4716e94777
go: github.com/gogo/protobuf upgrade => v1.3.2
go: golang.org/x/sync upgrade => v0.0.0-20201207232520-09787c993a3a
go: github.com/gobuffalo/envy upgrade => v1.9.0
go: golang.org/x/time upgrade => v0.0.0-20201208040808-7e3f01d25324
go: github.com/sirupsen/logrus upgrade => v1.7.0
go: github.com/lib/pq upgrade => v1.9.0
go: github.com/prometheus/client_golang upgrade => v1.9.0
go: github.com/knq/sysutil upgrade => v1.0.0
go: github.com/andybalholm/cascadia upgrade => v1.2.0
go: github.com/pkg/errors upgrade => v0.9.1
go: google.golang.org/protobuf upgrade => v1.25.0
go: github.com/google/uuid upgrade => v1.2.0
go: github.com/prometheus/client_model upgrade => v0.2.0
go: github.com/gobwas/httphead upgrade => v0.1.0
go: github.com/hidal-go/hidalgo upgrade => v0.0.0-20201109092204-05749a6d73df
go: github.com/go-kit/kit upgrade => v0.10.0
go: github.com/gobwas/pool upgrade => v0.2.1
go: github.com/PuerkitoBio/goquery upgrade => v1.6.1
go: github.com/caffix/queue upgrade => v0.0.0-20210106184330-1d2e72b64fa0
go: github.com/spf13/pflag upgrade => v1.0.5
go: github.com/chromedp/chromedp upgrade => v0.6.5
go: github.com/go-sql-driver/mysql upgrade => v1.5.0
go: github.com/hashicorp/errwrap upgrade => v1.1.0
go: github.com/cayleygraph/quad upgrade => v1.2.4
go: github.com/AndreasBriese/bbloom upgrade => v0.0.0-20190825152654-46b345b51c96
go: github.com/hashicorp/go-multierror upgrade => v1.1.0
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/fatih/color upgrade => v1.10.0
go: github.com/mattn/go-colorable upgrade => v0.1.8
go: github.com/geziyor/geziyor upgrade => v0.0.0-20210128175025-129402d754a6
go: github.com/gobwas/ws upgrade => v1.0.4
go: github.com/caffix/stringset upgrade => v0.0.0-20201218054545-37e95a70826c
go get: github.com/knq/sysutil@v0.0.0-20191005231841-15668db23d08 updating to
	github.com/knq/sysutil@v1.0.0: parsing go.mod:
	module declares its path as: github.com/chromedp/sysutil
	        but was required as: github.com/knq/sysutil
$ 

```

**Comment by jimen0** [comment]
Hi @riramar,

You shouldn't be using modules in gopath mode at this point. Latest release works fine in modules mode (default mode as per current Go stable release).

```console
$ docker run --rm -it golang:latest sh
# cd / && mkdir project && cd project && go mod init project
go: creating new go.mod: module project
# go get -v github.com/OWASP/Amass/v3@v3.11.3
go: downloading github.com/OWASP/Amass/v3 v3.11.3
# cat go.mod
module project

go 1.15

require github.com/OWASP/Amass/v3 v3.11.3 // indirect
```

I think Amass docs are outdated compared with current Go best practices.

**Comment by riramar** [comment]
hi @jimen0,

Thanks a lot for explanation! I was able to upgrade now.
